### ISSUE TITLE
In v0.2.2 disabling net adapters is not possible under non-admin account

### ISSUE THREAD

**Issue by alex-ilin** [JLospinoso/beamgun#7]
I've installed v0.2.2 from the MSI package. I'm running a non-admin account on my Win8.1 machine. The application's "Disable new net adapters" and "Disable USB Storage" (why is the last word capitalized?) options are disabled. I thought it was due to me being a non-admin, but could not verify due to issue #6.

**Comment by JLospinoso** [comment]
@AlexIljin This is expected behavior; when you are not running with administrator privileges, it is not possible to disable devices (you can verify this by attempting to disable a device in the Device Manager). Likewise, the registry key needed to disable USB storage can only be accessed with administrator privileges.

I'll update the "Documentation" (the README) to reflect this.

Thanks for reporting!

**Comment by JLospinoso** [comment]
Done!

https://github.com/JLospinoso/beamgun/commit/77501b13ceb375dc237290f2a038f07b97e46a5f

**Comment by alex-ilin** [comment]
@JLospinoso: would it be possible to run the app (or a version of it) as a service? That way it would work for limited users and have all the access rights necessary to control the devices.

**Comment by JLospinoso** [comment]
@AlexIljin, it's a good idea, but running as a service puts us in Session 0, outside of the active user. So we could do things like monitor and disable hardware, I'm not sure whether LockWorkstation would work. And SetWindowsHookEx definitely doesn't work. Finally, we wouldn't have access to the user's Systray and so they wouldn't be able to interact with the application

I've thought abuot splitting out the architecture so that you can run all the Administrator-level code in a service and interact with the user through low-user code. Maybe it's time to try it.. I'll open a ticket.
